Fix http constants and status codes #6
rehacktive/caffeine pull request #7
Opened 2021-11-18 11:37 UTC by ehsundar

- method names
- status codes
- error messages

2021-11-18 11:38 UTC, ehsundar commented
#6

2021-11-18 17:32 UTC, ehsundar commented
I plan to refactor your storage impls. I think its better to have the interface def under database package. Also each implementation must move to its own package with specialized constructor

2021-11-19 13:34 UTC, rehacktive requested changes

2021-11-19 13:34 UTC, rehacktive commented on database/fs/fs.go
> +package fs
I would keep this in the same package (in the end it's just another "database" implementation)

2021-11-19 13:36 UTC, rehacktive commented
> I also would like to refactor storage impls. I think its better to have the interface def under database package. Also each implementation must move to its own package with specialized constructor

having a common interface with no specific constructor makes the code simple. this can be changed when specifically necessary.

2021-11-20 09:06 UTC, rehacktive commented
hello - could you please rebase and make the small change? I'll be happy to merge then. thanks @ehsundar

2021-11-20 09:44 UTC, ehsundar commented
Hey. I'll consider the requested changes today.

2021-11-20 11:34 UTC, rehacktive approved these changes
all good :) thanks a lot!

2021-11-20 11:34 UTC, merged